### ISSUE TITLE
PLEASE READ >> GA package name request from university student

### ISSUE THREAD

**Issue by EREPPLab** [mdscruggs/ga#1]
Hey sir,

I was wondering if you would be willing to give up the package name “GA”. Im a junior computer science student at Embry Riddle University in Daytona Beach. I've developed a useful and easy to use GA program in python and want to develop a package so that I can share it to the world and make it easier for others to use a genetic algorithm.

Here is the current hidden version of our GA project.
https://github.com/EREPPLab/Test_WIKI

Here is the wiki
https://github.com/EREPPLab/Test_WIKI/wiki

It still needs some work but I’ve already got some good feedback and people like it.

My email is danielwilczak101@gmail.com

Thank you,
Daniel Wilczak

**Comment by mdscruggs** [comment]
@EREPPLab thanks for the inquiry, and your work looks cool, but I'd prefer not to rename this project. While I don't actively maintain this project (as you can probably tell) it has been published to PyPI: https://pypi.org/project/ga/. If anyone happens to be using this library, they will potentially experience confusion if this GitHub repo is renamed; if I remove it from PyPI, their own projects may break. I may also choose to upgrade this project to a more recent version of Python for some point, and I refer to this project in some places as part of my personal project portfolio.

I took a brief look at your project and suggest naming it something that includes "robotics" so users can find it when searching for "python" + "robotics" + "genetic algorithms" etc.
